name: staging-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run Unit Tests
        run: go test -v ./**/*test.go
  
  deploy-staging-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push staging image
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            $GITHUB_REPOSITORY:latest
  
    deploy-staging-api:
    runs-on: ubuntu-latest
    needs: deploy-staging-image
    steps:
      - name: Deploy To Staging Environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_SECRET }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/api-staging
            ./deploy/deploy-staging.sh
